# Generated by Django 4.2.2 on 2023-07-19 23:16

import BackOffice.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome_animal', models.CharField(max_length=250, verbose_name='Nome do animal')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='P', max_length=1, verbose_name='Porte')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
            ],
            options={
                'verbose_name_plural': 'Animais',
                'ordering': ('id_animal',),
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id_atendimento', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_atendimento', models.CharField(choices=[('1', 'PetShop'), ('2', 'Atendimento Médico'), ('3', 'Intervenção Cirúrgica')], default='1', max_length=5, verbose_name='Categoria')),
                ('titulo_atendimento', models.CharField(max_length=250, verbose_name='Titulo')),
                ('descricao_atendimento', models.TextField(verbose_name='Descrição')),
                ('urgencia', models.CharField(choices=[('1', 'Baixa'), ('2', 'Média'), ('3', 'Alta'), ('4', 'Urgente')], default='1', max_length=5, verbose_name='Urgência')),
                ('status_atendimento', models.CharField(choices=[('1', 'Aguardando Atendimento'), ('2', 'Em Atendimento'), ('3', 'Em Espera'), ('4', 'Finalizado')], default=1, max_length=5, verbose_name='Status do atendimento')),
                ('status_pagamento', models.CharField(choices=[('1', 'Aguardando Pagamento'), ('2', 'Pagamento Realizado')], default='1', max_length=5, verbose_name='Status do pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_inicio', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Iniciado em')),
                ('data_encerramento', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Encerrado em')),
                ('data_pagamento', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='Pagamento realizado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_atendimento', to='BackOffice.animal', verbose_name='Animal')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_animal_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Atendimentos',
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('nome_clinica', models.CharField(max_length=250, verbose_name='Nome da Clínica')),
                ('cnpj', models.CharField(max_length=20, validators=[BackOffice.models.validate_cnpj], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(max_length=20, verbose_name='Inscrição Municipal')),
                ('endereco', models.CharField(max_length=512, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=9, validators=[BackOffice.models.validate_cep], verbose_name='CEP')),
                ('municipio', models.CharField(max_length=250, verbose_name='Município')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_clinica', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario_ult_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_clinica', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por')),
            ],
            options={
                'verbose_name_plural': 'Clínicas',
                'ordering': ('id_clinica',),
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id_forma_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_forma_pagamento', models.CharField(max_length=250, verbose_name='Forma de pagamento')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo da forma de pagamento')),
                ('dados_integracao', models.TextField(verbose_name='Dados para integração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
                ('id_clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinica_forma_pagamento', to='BackOffice.clinica', verbose_name='Clínica')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_forma_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario_ult_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_forma_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por')),
            ],
            options={
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ('id_forma_pagamento',),
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vacina', models.CharField(max_length=250, verbose_name='Vacina')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
                ('id_clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinica_vacina', to='BackOffice.clinica', verbose_name='Clínica')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_atendimento_vacina', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario_ult_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_atendimento_vacina', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por')),
            ],
            options={
                'verbose_name_plural': 'Vacinas',
                'ordering': ('id_vacina',),
            },
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id_tipo_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo_animal', models.CharField(max_length=250, verbose_name='Tipo de Animal')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_tipo_animal', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario_ult_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_tipo_animal', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Animal',
                'ordering': ('id_tipo_animal',),
            },
        ),
        migrations.CreateModel(
            name='RacaAnimal',
            fields=[
                ('id_raca', models.AutoField(primary_key=True, serialize=False)),
                ('nome_raca', models.CharField(max_length=250, verbose_name='Raça')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_animal_raca', to='BackOffice.tipoanimal', verbose_name='Tipo de Animal')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_raca', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario_ult_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_raca', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por')),
            ],
            options={
                'verbose_name_plural': 'Raças de Animal',
                'ordering': ('id_raca',),
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_pagamento', models.DateTimeField(verbose_name='Data do pagamento')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_ult_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última alteração em')),
                ('id_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_pagamento', to='BackOffice.atendimento', verbose_name='Atendimento')),
                ('id_forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forma_pagamento', to='BackOffice.formapagamento', verbose_name='Forma de pagamento')),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('usuario_ult_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos',
                'ordering': ('id_pagamento',),
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinica_atendimento', to='BackOffice.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='id_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medico_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Médico Veterinário'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='usuario_criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='usuario_ult_atualizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='vacinas',
            field=models.ManyToManyField(default=None, to='BackOffice.vacina', verbose_name='Vacinas'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinica_animal', to='BackOffice.clinica', verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='animal',
            name='id_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_animal', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raca_animal', to='BackOffice.racaanimal', verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipo_animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_animal', to='BackOffice.tipoanimal', verbose_name='Tipo de Animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='usuario_criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_criador_animal', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='animal',
            name='usuario_ult_atualizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_alteracao_animal', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração feita por'),
        ),
    ]
