# Generated by Django 4.2.2 on 2023-07-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='vacinas',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='BackOffice.vacina', verbose_name='Vacina'),
        ),
    ]
