# Generated by Django 4.2.2 on 2023-07-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackOffice', '0002_alter_atendimento_vacinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapagamento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo da forma de pagamento'),
        ),
    ]
